name: Node.js Package

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: |
          yarn install --immutable
          yarn build
          yarn lint
          yarn playwright install
          yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable
      - run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.SESAMECARE_OSS_NPM_TOKEN }}
        run: |
          yarn dlx semantic-release
